name: Push on Master jobs

on:
  push:
    branches: [ main ]

jobs:
  automaticpublish:
    name: Automatic Mod Browser Publish Integration
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
       
      # Upload artifact for all builds
      - uses: actions/upload-artifact@v2
        with:
          name: .tmod file
          path: ~/tModLoader/ModLoader/Mods/RandomStats.tmod
